export const blogConfig = {
  posts: [
    {
      source: "AI/Agent Skills 完全指南.md",
      slug: "agent-skills",
      title: "Agent Skills 完全指南",
      summary: "系统梳理 Agent Skill 的结构、触发方式、渐进式加载和跨平台边界。",
      featured: true,
    },
    {
      source: "AI/Agent MCP 完全指南.md",
      slug: "agent-mcp",
      title: "Agent MCP 完全指南",
      summary: "从协议层、工具调用、资源暴露和权限边界理解 MCP 在 Agent 系统里的位置。",
      featured: true,
    },
    {
      source: "AI/Agent Plugin 完全指南.md",
      previousSources: ["AI/Agent Plugin 完全指南 v2.md"],
      slug: "agent-plugin",
      title: "Agent Plugin 完全指南",
      summary: "系统梳理 Plugin 的组件模型、目录、加载、分发、安全与跨端差异。",
      featured: true,
    },
    {
      source: "AI/分享/把需求写成可验证的 Spec.md",
      slug: "verifiable-spec",
      title: "把需求写成可验证的 Spec",
      summary: "用 Spec、用例、Mock、脚本和证据标准，把复杂需求变成可执行、可复查的交付闭环。",
    },
    {
      source: "AI/Codex 低侵入扩展架构思想（CMUX×Ducx）.md",
      slug: "codex-low-intrusion-extension",
      title: "Codex 低侵入扩展架构思想",
      summary: "从 CMUX 与 Ducx 提炼一种不改内核、用稳定入口扩展复杂系统的架构心智模型。",
    },
    {
      source: "AI/Codex config 配置说明.md",
      slug: "codex-config",
      title: "Codex config 配置说明",
      summary: "梳理 Codex 配置加载、模型提供方、权限策略、MCP 和插件相关字段。",
    },
    {
      source: "AI/AI 客户端模型请求代理与中转链路.md",
      slug: "ai-client-request-proxy",
      title: "AI 客户端模型请求代理与中转链路",
      summary: "解释模型客户端、OpenAI-compatible 入口、本地代理和第三方中转之间的请求路径。",
    },
    {
      source: "Android/架构/Wrapper包装层：用稳定入口隔开复杂世界.md",
      slug: "wrapper-stable-entry",
      title: "Wrapper 包装层：用稳定入口隔开复杂世界",
      summary: "用 Wrapper 收住复杂依赖、失败分支和平台差异，让核心代码只面对稳定语义。",
    },
    {
      source: "网络/macOS 网络可达性与自动挂载机制.md",
      slug: "macos-network-automount",
      title: "macOS 网络可达性与自动挂载机制",
      summary: "从路由、可达性判断和挂载策略理解 macOS 自动连接网络资源的工作方式。",
    },
  ],
  imageAlts: {
    "agent-skill-progressive-loading.svg": "Agent Skill 渐进式加载与按需读取流程",
    "agent-skill-authoring-gate.svg": "Agent Skill 编写、验证与发布门禁",
    "agent-mcp-layer-chain.svg": "MCP 在 Agent 系统中的分层链路",
    "agent-mcp-connection-problem.svg": "未使用 MCP 时客户端与外部系统的多对多连接",
    "agent-mcp-role-call-sequence.svg": "MCP Host、Client 与 Server 的工具调用时序",
    "agent-mcp-server-primitives.svg": "MCP Server 的 Tools、Resources 与 Prompts 能力",
    "agent-mcp-protocol-layers.svg": "MCP 协议分层结构",
    "agent-mcp-lifecycle.svg": "MCP 连接生命周期",
    "agent-mcp-tool-call-flow.svg": "MCP 工具调用完整流程",
    "agent-mcp-function-calling-bridge.svg": "Function Calling 与 MCP 的衔接关系",
    "agent-mcp-skill-composition.svg": "Agent Skill 与 MCP 的组合关系",
    "agent-mcp-plugin-composition.svg": "Agent Plugin 与 MCP 的组合关系",
    "agent-mcp-filesystem-pattern.svg": "本地文件系统型 MCP 模式",
    "agent-mcp-doc-pattern.svg": "远程文档型 MCP 模式",
    "agent-mcp-data-pattern.svg": "数据分析型 MCP 模式",
    "agent-plugin-component-model.svg": "Agent Plugin 组件模型",
    "agent-plugin-component-choice.svg": "Agent Plugin 组件选型",
    "agent-plugin-runtime-lifecycle.svg": "Agent Plugin 运行时生命周期",
    "agent-plugin-mental-model.svg": "Agent Plugin 心智模型",
    "agent-plugin-two-hosts.svg": "Codex 与 Claude Code Plugin 的双宿主差异",
    "spec-sdd-to-verifiable-spec.svg": "从 SDD 到可验证 Spec 的需求交付流程",
    "spec-verifiable-contract.svg": "可验证 Spec 的契约结构",
    "spec-delivery-loop.svg": "Spec 驱动的交付验证闭环",
    "spec-suitable-boundary.svg": "适合使用可验证 Spec 的任务边界",
    "feedads-mock-scheme-principle-gpt.png": "FeedAds Mock Scheme 原理示意图",
    "spec-core-conclusion-gpt.png": "可验证 Spec 的核心结论",
    "codex-config-load-order.svg": "Codex 配置加载顺序",
    "codex-model-provider-request-path.svg": "Codex 模型提供方请求链路",
    "agent-message-request-sequence.svg": "Agent 消息请求时序",
    "agent-request-anatomy.svg": "Agent 请求结构",
    "agent-api-family-comparison.svg": "Agent API 家族对比",
    "openai-compatible-gateway-fields.svg": "OpenAI 兼容网关字段映射",
    "openai-native-endpoints-cheatsheet.png": "OpenAI 原生端点速查",
    "anthropic-claude-native-endpoints-cheatsheet.png": "Anthropic Claude 原生端点速查",
    "macos-network-automount-layers.png": "macOS 网络磁盘自动挂载分层架构",
  },
}
